#This is for you to play around with the code not the one you share with your team
#You cant have two containers running at the same time with the same name so all the name APART FROM HOST have -test 
#Also the port numbers have been altered 

name: project-app-testing #This has a name 

services:
  app-test:
    build: ./app
    container_name: web-app-test
    hostname: web-app
    volumes: ["./app/src:/appcode"]
    ports:
      - 8502:8501

  api-test:
    build: ./api
    container_name: web-api-test
    hostname: web-api
    volumes: ["./api:/apicode"]
    ports:
      - 4001:4000

  db-test:
    env_file:
      - ./api/.env
    image: mysql:9
    container_name: mysql-db-test
    hostname: db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3201:3306
